spring:
  application:
    name: simple-board

  datasource:
    url: {URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: {USER_NAME}
    password: {PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
      dialect: org.hibernate.dialect.MySQL8Dialect